"""empty message

Revision ID: 3e1d0083687a
Revises: 1bafa62ab931
Create Date: 2024-03-21 16:55:35.448488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1d0083687a'
down_revision = '1bafa62ab931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questiona', sa.String(), nullable=False))
        batch_op.drop_constraint('question_question_key', type_='unique')
        batch_op.create_unique_constraint(None, ['questiona'])
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('question_question_key', ['question'])
        batch_op.drop_column('questiona')

    # ### end Alembic commands ###
