"""empty message

Revision ID: 4ca83bf3bf18
Revises: 5ed59b8d1419
Create Date: 2024-03-21 17:19:08.754591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca83bf3bf18'
down_revision = '5ed59b8d1419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questiona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questiona', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questiona')
    # ### end Alembic commands ###
